### ISSUE TITLE
Misspell?

### ISSUE THREAD

**Issue by jusski** [VladislavSevruk/GraphQlRequestBodyGenerator#36]
![image](https://user-images.githubusercontent.com/8794405/176844604-aa161932-a294-4eb5-b6e6-6154544774e1.png)

**Comment by VladislavSevruk** [comment]
Yes, thank you

**Comment by VladislavSevruk** [comment]
Fixed at https://github.com/VladislavSevruk/GraphQlRequestBodyGenerator/pull/38
