### ISSUE TITLE
generate query operation name with bind parameters

### ISSUE THREAD

**Issue by tzvetkovg** [VladislavSevruk/GraphQlRequestBodyGenerator#37]
Is there an ability to generate the query with bind parameters and operation name. For example

instead of 

`{someQuery(param1:\"COMPANY\"{results{myVal}}}`
 
to generate 

`query testQuery(param1: String!) {someQuery(param1:$param1{results{myVal}}}`

**Comment by VladislavSevruk** [comment]
Right now you can generate query with bind parameters but it'll be anonymous
```
query($param1: String!) {someQuery(param1:$param1){results{myVal}}}
```
Please refer to [variables](https://github.com/VladislavSevruk/GraphQlRequestBodyGenerator#variables) section at ReadMe.md

**Comment by VladislavSevruk** [comment]
Ability to add alias was implemented at https://github.com/VladislavSevruk/GraphQlRequestBodyGenerator/pull/39 and will be present at 1.0.11 version

**Comment by VladislavSevruk** [comment]
Since version 1.0.12 you can use ``UnwrappedGqlRequestBodyGenerator`` instead of ``GqlRequestBodyGenerator`` to generate unwrapped to json GraphQL request bodies.
